version: '3.8'

services:
  backend:
    build: ./backend
    container_name: java-backend
    ports:
      - "3001:8080"
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "8082:80"
    restart: unless-stopped
    depends_on:
      - backend
