name: CI/CD Java + Vue (Self-Hosted)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and run containers
        run: |
          docker compose down || true
          docker compose build
          docker compose up -d
